### ISSUE TITLE
Installed fine but "yarn test" fails

### ISSUE THREAD

**Issue by tbarbaro** [kentcdodds/asts-workshop#6]
Here are the first few errors.

tom:asts-workshop Tom$ yarn test
yarn test v0.22.0
$ nps test
nps executing: jest --config=exercises/jest.config.json --coverage
 FAIL  exercises/01_eslint.test.js
  ● I submitted my elaboration and feedback

    expect(received).toBe(expected)

    Expected value to be (using ===):
      false
    Received:
      true

      at Object.<anonymous>.test (exercises/01_eslint.test.js:16:16)

 FAIL  exercises/02_eslint.test.js
  ● I submitted my elaboration and feedback

    expect(received).toBe(expected)

    Expected value to be (using ===):
      false
    Received:
      true

      at Object.<anonymous>.test (exercises/02_eslint.test.js:25:16)

 FAIL  exercises/03_eslint.test.js
  ● no-blockless-if › invalid › if (foo) foo()

    AssertionError: Should have 1 error but had 0: []

      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:472:24)
      at Object.RuleTester.it (node_modules/eslint/lib/testers/rule-tester.js:557:25)

  ● no-blockless-if › invalid › if (foo)
          foo()

    AssertionError: Should have 1 error but had 0: []

      at testInvalidTemplate (node_modules/eslint/lib/testers/rule-tester.js:472:24)
      at Object.RuleTester.it (node_modules/eslint/lib/testers/rule-tester.js:557:25)

  ● no-blockless-if › invalid › if (foo && bar)
          foo()
          bar()

**Comment by kentcdodds** [comment]
Thanks for reporting this! I'll get to work on it!
